export const countriesData = [
  { label: "ОАЭ", value: "AE" },
  { label: "Афганистан", value: "AF" },
  { label: "Албания", value: "AL" },
  { label: "Андорра", value: "AD" },
  { label: "Ангола", value: "AO" },
  { label: "Антигуа и Барбуда", value: "AG" },
  { label: "Аргентина", value: "AR" },
  { label: "Армения", value: "AM" },
  { label: "Австралия", value: "AU" },
  { label: "Австрия", value: "AT" },
  { label: "Азербайджан", value: "AZ" },

  { label: "Багамы", value: "BS" },
  { label: "Бахрейн", value: "BH" },
  { label: "Бангладеш", value: "BD" },
  { label: "Барбадос", value: "BB" },
  { label: "Беларусь", value: "BY" },
  { label: "Бельгия", value: "BE" },
  { label: "Белиз", value: "BZ" },
  { label: "Бенин", value: "BJ" },
  { label: "Бутан", value: "BT" },
  { label: "Боливия", value: "BO" },
  { label: "Босния и Герцеговина", value: "BA" },
  { label: "Ботсвана", value: "BW" },
  { label: "Бразилия", value: "BR" },
  { label: "Бруней-Даруссалам", value: "BN" },
  { label: "Болгария", value: "BG" },
  { label: "Буркина-Фасо", value: "BF" },
  { label: "Бурунди", value: "BI" },

  { label: "Кабо-Верде", value: "CV" },
  { label: "Камерун", value: "CM" },
  { label: "Канада", value: "CA" },
  { label: "Центрально-Африканская Республика", value: "CF" },
  { label: "Чили", value: "CL" },
  { label: "Колумбия", value: "CO" },
  { label: "Конго", value: "CD" },
  { label: "Коста-Рика", value: "CR" },
  { label: "Кот д'Ивуар", value: "CI" },
  { label: "Куба", value: "CU" },
  { label: "Кипр", value: "CY" },
  { label: "Чешская Республика", value: "CZ" },
  { label: "Конго", value: "CG" },
  { label: "Китай", value: "CH" },

  { label: "Алжир", value: "DZ" },
  { label: "Дания", value: "DK" },
  { label: "Джибути", value: "DJ" },
  { label: "Доминика", value: "DM" },
  { label: "Доминиканская Республика", value: "DO" },
  { label: "Германия", value: "DE" },

  { label: "Гаити", value: "HT" },
  { label: "Гондурас", value: "HN" },
  { label: "Венгрия", value: "HU" },
  { label: "Хорватия", value: "HR" },

  { label: "Исландия", value: "IS" },
  { label: "Остров Мэн", value: "IM" },
  { label: "Индонезия", value: "ID" },
  { label: "Иран", value: "IR" },
  { label: "Ирак", value: "IQ" },
  { label: "Ирландия", value: "IE" },
  { label: "Израиль", value: "IL" },
  { label: "Италия", value: "IT" },

  { label: 'Финляндия', value: 'FI' },
  { label: 'Франция', value: 'FR' },

  { label: "Габон", value: "GA" },
  { label: 'Англия', value: 'GB' },
  { label: "Гамбия", value: "GM" },
  { label: "Грузия", value: "GE" },
  { label: "Гана", value: "GH" },
  { label: "Греция", value: "GR" },
  { label: "Гренада", value: "GD" },
  { label: "Гватемала", value: "GT" },
  { label: "Гвинея", value: "GN" },
  { label: "Гвинея-Бисау", value: "GW" },
  { label: "Гайана", value: "GY" },
  { label: "Экваториальная Гвинея", value: "GQ" },

  { label: "Ямайка", value: "JM" },
  { label: "Япония", value: "JP" },
  { label: "Иордан", value: "JO" },

  { label: "Казахстан", value: "KZ" },
  { label: "Камбоджа", value: "KH" },
  { label: "Коморы", value: "KM" },
  { label: "Кения", value: "KE" },
  { label: "Кирибати", value: "KI" },
  { label: "Сент-Китс и Невис", value: "KN" },
  { label: "Кувейт", value: "KW" },
  { label: "Киргизия", value: "KG" },
  { label: "Южная Корея", value: "KR" },

  { label: "Лаос", value: "LA" },
  { label: "Латвия", value: "LV" },
  { label: "Ливан", value: "LB" },
  { label: "Лесото", value: "LS" },
  { label: "Либерия", value: "LR" },
  { label: "Ливия", value: "LY" },
  { label: "Лихтенштейн", value: "LI" },
  { label: "Литва", value: "LT" },
  { label: "Люксембург", value: "LU" },
  { label: "Сент-Люсия", value: "LC" },
  { label: "Шри-Ланка", value: "LK" },

  { label: "Мадагаскар", value: "MG" },
  { label: "Малави", value: "MW" },
  { label: "Малайзия", value: "MY" },
  { label: "Мальдивы", value: "MV" },
  { label: "Мали", value: "ML" },
  { label: "Мальта", value: "MT" },
  { label: "Маршалловы острова", value: "MH" },
  { label: "Мавритания", value: "MR" },
  { label: "Маврикий", value: "MU" },
  { label: "Мексика", value: "MX" },
  { label: "Монако", value: "MC" },
  { label: "Монголия", value: "MN" },
  { label: "Черногория", value: "ME" },
  { label: "Марокко", value: "MA" },
  { label: "Мозамбик", value: "MZ" },
  { label: "Мьянма", value: "MM" },
  { label: "Республика Македония", value: "MK" },
  { label: "Молдова", value: "MD" },

  { label: "Намибия", value: "NA" },
  { label: "Науру", value: "NR" },
  { label: "Непал", value: "NP" },
  { label: "Нидерланды", value: "NL" },
  { label: "Новая Зеландия", value: "NZ" },
  { label: "Никарагуа", value: "NI" },
  { label: "Нигер", value: "NE" },
  { label: "Нигерия", value: "NG" },
  { label: "Норвегия", value: "NO" },

  { label: "Оман", value: "OM" },

  { label: "Пакистан", value: "PK" },
  { label: "Палау", value: "PW" },
  { label: "Панама", value: "PA" },
  { label: "Папуа-Новая Гвинея", value: "PG" },
  { label: "Парагвай", value: "PY" },
  { label: "Перу", value: "PE" },
  { label: "Филиппины", value: "PH" },
  { label: "Польша", value: "PL" },
  { label: "Португалия", value: "PT" },

  { label: "Катар", value: "QA" },

  { label: "Румыния", value: "RO" },
  { label: "Россия", value: "RU" },
  { label: "Руанда", value: "RW" },
  { label: "Сербия", value: "RS" },

  { label: "Саудовская Аравия", value: "SA" },
  { label: "Соломоновы острова", value: "SB" },
  { label: "Сейшелы", value: "SC" },
  { label: "Судан", value: "SD" },
  { label: "Швеция", value: "SE" },
  { label: "Сингапур", value: "SG" },
  { label: "Словения", value: "SI" },
  { label: "Словакия", value: "SK" },
  { label: "Сьерра-Леоне", value: "SL" },
  { label: "Сан-Марино", value: "SM" },
  { label: "Эль-Сальвадор", value: "SV" },
  { label: "Суринам", value: "SR" },
  { label: "Сирийская Арабская Республика", value: "SY" },
  { label: "Южный Судан", value: "SS" },
  { label: "Сан-Томе и Принсипи", value: "ST" },
  { label: "Сенегал", value: "SN" },
  { label: "Сомали", value: "SO" },
  { label: "Эсватини", value: "SZ" },

  { label: "Таджикистан", value: "TJ" },
  { label: "Таиланд", value: "TH" },
  { label: "Тимор-Лесте", value: "TL" },
  { label: "Того", value: "TG" },
  { label: "Тонга", value: "TO" },
  { label: "Тринидад и Тобаго", value: "TT" },
  { label: "Тунис", value: "TN" },
  { label: "Турция", value: "TR" },
  { label: "Туркмения", value: "TM" },
  { label: "Тувалу", value: "TV" },
  { label: "Чад", value: "TD" },

  { label: "США", value: "US" },
  { label: "Уганда", value: "UG" },
  { label: "Украина", value: "UA" },
  { label: "Уругвай", value: "UY" },
  { label: "Узбекистан", value: "UZ" },

  { label: "Вануату", value: "VU" },
  { label: "Венесуэла", value: "VE" },
  { label: "Вьетнам", value: "VN" },
  { label: "Сент-Винсент и Гренадины", value: "VC" },

  { label: "Самоа", value: "WS" },

  { label: "Вьетнам", value: "YZ" },
  { label: "Йемен", value: "YE" },

  { label: "Замбия", value: "ZM" },
  { label: "Зимбабве", value: "ZW" },
  { label: "Южная Африка", value: "ZA" },
].map(country => ({
  ...country,
  value: country.value.toLocaleLowerCase()
}));
